# Generated by Django 5.2.1 on 2025-05-23 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.courses')),
            ],
            options={
                'db_table': 'Enrollments',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade_value', models.CharField(max_length=255)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollments')),
            ],
            options={
                'db_table': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('identity_no', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('class_level', models.CharField(default=1, max_length=1)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.departments')),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.AddField(
            model_name='enrollments',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students'),
        ),
    ]
