# Generated by Django 5.2.1 on 2025-05-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enrollments_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollments',
            name='semester',
        ),
    ]
