# Generated by Django 5.1.6 on 2025-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_enrollments_grades_students_delete_deneme_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrollments',
            table='Enrollments',
        ),
        migrations.AlterModelTable(
            name='grades',
            table='Grades',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Students',
        ),
    ]
