# Generated by Django 5.2.1 on 2025-05-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_enrollments_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='exam',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
