# Generated by Django 5.2.1 on 2025-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_grades_exam'),
    ]

    operations = [
    ]
