# Generated by Django 5.2.1 on 2025-05-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_grades_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='grades',
            name='grade_value',
        ),
        migrations.AddField(
            model_name='grades',
            name='final',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grades',
            name='midterm',
            field=models.IntegerField(null=True),
        ),
    ]
