# Generated by Django 5.2.1 on 2025-05-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_grades_grade_value'),
        ('students', '0005_remove_grades_exam_remove_grades_grade_value_and_more'),
    ]

    operations = [
    ]
