# Generated by Django 5.2.1 on 2025-05-27 19:00

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_merge_20250527_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='grade_value',
        ),
    ]
