# Generated by Django 5.2.1 on 2025-05-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_grades_grade_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
