# Generated by Django 5.1.6 on 2025-05-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=255)),
                ('building_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
