# Generated by Django 5.2.1 on 2025-05-23 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructors'),
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.departments'),
        ),
        migrations.AddField(
            model_name='departments',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.faculties'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.classrooms'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.courses'),
        ),
    ]
