# Generated by Django 5.1.6 on 2025-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='classrooms',
            table='Classrooms',
        ),
        migrations.AlterModelTable(
            name='courses',
            table='Courses',
        ),
        migrations.AlterModelTable(
            name='departments',
            table='Departments',
        ),
        migrations.AlterModelTable(
            name='faculties',
            table='Faculties',
        ),
        migrations.AlterModelTable(
            name='schedules',
            table='Schedules',
        ),
    ]
