# Generated by Django 5.2.1 on 2025-05-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.CharField(default='Unknown', max_length=25),
        ),
    ]
