# Generated by Django 5.2.1 on 2025-05-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_courses_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_code',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
