# Generated by Django 5.2.1 on 2025-05-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_courses_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
