# Generated by Django 5.2.1 on 2025-05-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_schedules_end_time_alter_schedules_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
