# Generated by Django 5.2.1 on 2025-05-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
