# Generated by Django 5.1.6 on 2025-05-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instructors',
            table='Instructors',
        ),
    ]
