# Generated by Django 5.2.1 on 2025-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='instructors',
            name='office',
            field=models.CharField(default='No Office Available', max_length=20),
        ),
        migrations.AddField(
            model_name='instructors',
            name='title',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instructors',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
